---
title: "Explore"
output: html_notebook
---

Loading libraries and functions
```{r}
library(tidyverse)
source("function.R") # for F1 calculation
```

# assuming all calls are true calls
```{r}
vcf <- read.csv("output/snv-parse-syn1.csv")
head(vcf)
```

```{r}
truth = read.table("data/syn1/syn1_truth.bed") 
mypred = vcf[,1:3]

calc.F1(mypred, truth)
```

```{r}

## truth information
# data <- c("syn1","syn2","syn3","syn4","syn5","real1","real2_part1")
# truthfiles <- paste0("data/", data, "/", data, "_truth.bed")
# truthfiles[7] = "data/real2_part1/real2_truth_chr1to5.bed"
# vcffiles <- paste0("output/snv-parse-", data, ".csv")
# 
# for (i in 1:7){
#   mypred <- read.csv(vcffiles[i])
#   truth = read.table(truthfiles[i]) 
#   colnames(truth) = colnames(mypred)[1:3]
#   left_join(truth, mypred) %>%
#     write.csv(., paste0("truth/truth-", data[i], ".csv"), row.names = F)
# }

##
# setwd("./data/real1/")
# mutect2 <- Sys.glob("*mutect*vcf.gz")
# freebayes <- Sys.glob("*freebayes*vcf.gz")
# varscan <- Sys.glob("*varscan*vcf.gz")
# vardict <- Sys.glob("*vardict*vcf.gz")
# x<-list(mutect2,freebayes,varscan,vardict)
# 
# mutect2.tbi <- Sys.glob("*mutect*vcf.gz.tbi")
# freebayes.tbi <- Sys.glob("*freebayes*vcf.gz.tbi")
# varscan.tbi <- Sys.glob("*varscan*vcf.gz.tbi")
# vardict.tbi <- Sys.glob("*vardict*vcf.gz.tbi")
# tbi<-list(mutect2.tbi,freebayes.tbi,varscan.tbi,vardict.tbi)
# 
# library(VariantAnnotation)
# 
# ## checking info
# xx<-scanVcfHeader(x[[4]])
# c <- cbind(xx@header@listData[["INFO"]]@rownames,xx@header@listData[["INFO"]]@listData[["Description"]])
# View(c)
```


```{r}
data <- c("syn1","syn2","syn3","syn4","syn5","real1","real2_part1")
truthfiles <- paste0("data/", data, "/", data, "_truth.bed")
truthfiles[7] = "data/real2_part1/real2_truth_chr1to5.bed"
vcffiles <- paste0("output/snv-parse-", data, ".csv")

res <- data.frame(dataset = character(),
                  TP = integer(), FP = integer(), FN = integer(), Precision = numeric(), Recall = numeric(), F1 = numeric())

for (i in 1:7){
  mypred <- read.csv(vcffiles[i])[,1:3]
  truth = read.table(truthfiles[i]) 
  f1stats <- calc.F1(mypred, truth)
  res[i,] = c(data[i], f1stats)
}

res
```

# specific calls are true calls
- based on type of software used

## mutect2
```{r}
mutect2 <- data.frame(dataset = character(),
                  TP = integer(), FP = integer(), FN = integer(), Precision = numeric(), Recall = numeric(), F1 = numeric())

for (i in 1:7){
  mypred <- read.csv(vcffiles[i]) %>%
    filter(FILTER_Mutect2) %>%
    select(1:3)
  truth = read.table(truthfiles[i]) 
  f1stats <- calc.F1(mypred, truth)
  mutect2[i,] = c(data[i], f1stats)
}

mutect2
```
```{r}
mutect2[,1:4] %>% pivot_longer(.,cols = c("TP","FP","FN"), names_to = "accuracy", values_to = "count") %>%
  ggplot(., aes(x=dataset, y=count, fill=accuracy)) +
  geom_bar(stat = "identity", position = 'dodge')
```

## freebayes
```{r}
freebayes <- data.frame(dataset = character(),
                  TP = integer(), FP = integer(), FN = integer(), Precision = numeric(), Recall = numeric(), F1 = numeric())

for (i in 1:7){
  mypred <- read.csv(vcffiles[i]) %>%
    filter(FILTER_Freebayes) %>%
    select(1:3)
  truth = read.table(truthfiles[i]) 
  f1stats <- calc.F1(mypred, truth)
  freebayes[i,] = c(data[i], f1stats)
}

freebayes
```
```{r}
freebayes[,1:4] %>% pivot_longer(.,cols = c("TP","FP","FN"), names_to = "accuracy", values_to = "count") %>%
  ggplot(., aes(x=dataset, y=count, fill=accuracy)) +
  geom_bar(stat = "identity", position = 'dodge')
```

## Vardict
```{r}
vardict <- data.frame(dataset = character(),
                  TP = integer(), FP = integer(), FN = integer(), Precision = numeric(), Recall = numeric(), F1 = numeric())

for (i in 1:7){
  mypred <- read.csv(vcffiles[i]) %>%
    filter(FILTER_Vardict) %>%
    select(1:3)
  truth = read.table(truthfiles[i]) 
  f1stats <- calc.F1(mypred, truth)
  vardict[i,] = c(data[i], f1stats)
}

vardict
```
```{r}
vardict[,1:4] %>% pivot_longer(.,cols = c("TP","FP","FN"), names_to = "accuracy", values_to = "count") %>%
  ggplot(., aes(x=dataset, y=count, fill=accuracy)) +
  geom_bar(stat = "identity", position = 'dodge')
```

## Varscan
```{r}
varscan <- data.frame(dataset = character(),
                  TP = integer(), FP = integer(), FN = integer(), Precision = numeric(), Recall = numeric(), F1 = numeric())

for (i in 1:7){
  mypred <- read.csv(vcffiles[i]) %>%
    filter(FILTER_Varscan) %>%
    select(1:3)
  truth = read.table(truthfiles[i]) 
  f1stats <- calc.F1(mypred, truth)
  varscan[i,] = c(data[i], f1stats)
}

varscan
```

```{r}
varscan[,1:4] %>% pivot_longer(.,cols = c("TP","FP","FN"), names_to = "accuracy", values_to = "count") %>%
  ggplot(., aes(x=dataset, y=count, fill=accuracy)) +
  geom_bar(stat = "identity", position = 'dodge')
```



# checking consistencies in true calls
```{r}
# for (i in 1:7){
#   mypred <- read.csv(vcffiles[i]) # prediction
#   truth <- read.table(truthfiles[i]) # %>% # bed files
#     # mutate(prediction = 1) # add an additional column
#   left_join(mypred, truth, by = c("Chr", "START_POS_REF", "END_POS_REF")) %>%
#     # mutate(prediction = ifelse(is.na(prediction), 0, 1)) %>%
#     write.csv(., paste0("truth/truth-", data[i], ".csv"), row.names = F)
# }

eda <- function(file){
  check <- read.csv(file)
  x <- rowSums(check[,9:12])
  hist(x, main = "Number of detection")
  # ggplot(check, aes(x=m2_MQ)) + geom_bar()
  hist(check[,13], main = "mutect2 MQ", breaks = seq(0,70,by=0.5))
  print(range(check[,13], na.rm = T))
  hist(check[,14], main = "freebayes MQMR", breaks = seq(0,70,by=0.5))
  print(range(check[,14], na.rm = T))
  hist(check[,15], main = "varscan SSC", nclass = 50)
  hist(check[,16], main = "varscan SPV", nclass = 50)
  hist(check[,17], main = "vardict SSF", nclass = 50)
  hist(check[,18], main = "vardict MSI", nclass = 50)
  print(range(check[,18], na.rm = T))
}
```

```{r}
eda("truth/truth-real1.csv")

```
```{r}
eda("truth/truth-syn1.csv")
```

```{r}
eda("truth/truth-syn2.csv")
```
```{r}
eda("truth/truth-syn3.csv")
```
```{r}
eda("truth/truth-syn4.csv")
```

```{r}
eda("truth/truth-syn5.csv")
```
```{r}
eda("truth/truth-real2_part1.csv")
```

# preprocessing
```{r}
preprocess <- function(file, count=2, mapq=40, p.value=0.05, p.v = 1, msi=1){
  df <- read.csv(file)
  m = nrow(df)
  df <- df %>%
    mutate(m2_MQ = ifelse(is.na(m2_MQ), ifelse(!is.na(f_MQMR), f_MQMR, 0), m2_MQ),
           f_MQMR = ifelse(is.na(f_MQMR), ifelse(!is.na(m2_MQ), m2_MQ, 0), f_MQMR)) %>%
    mutate(avgMQ = (m2_MQ+f_MQMR)/2,
           vs_SPV = ifelse((vs_SPV < p.value)&(!is.na(vs_SPV)), TRUE, FALSE),
           vd_SSF = ifelse((vd_SSF < p.value)&(!is.na(vd_SSF)), TRUE, FALSE)) %>%
    transmute(Chr = Chr,
              START_POS_REF = START_POS_REF,
              END_POS_REF = END_POS_REF,
              FILTER = FILTER_Mutect2 + FILTER_Freebayes + FILTER_Vardict + FILTER_Varscan,
              MQ = ifelse(avgMQ > mapq, TRUE, FALSE),
              P.V = vs_SPV + vd_SSF,
              MSI = ifelse((vd_MSI > msi)&(!is.na(vd_MSI)), TRUE, FALSE)) %>%
    filter((FILTER >= count ) | (MQ | (P.V >= p.v) | MSI))
  print(paste("from:", m, "to:", nrow(df)))
  return(df)
}

# filtering(vcffiles[1])
```


```{r}
res <- data.frame(dataset = character(),
                  TP = integer(), FP = integer(), FN = integer(), Precision = numeric(), Recall = numeric(), F1 = numeric())

for (i in 1:7){
  mypred <- preprocess(vcffiles[i], p.v = 2)[,1:3]
  truth = read.table(truthfiles[i]) 
  print(paste("Truth calls:", nrow(truth)))
  f1stats <- calc.F1(mypred, truth)
  res[i,] = c(data[i], f1stats)
}

res
```

